version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DB}"
    networks:
      - internal

volumes:
  postgres-data:
    driver: local

networks:
  internal:
    driver: bridge
